### ISSUE TITLE
vDDoS Admin Monitor: Error 5xx 

### ISSUE THREAD

**Issue by robert1112** [duy13/vDDoS-Protection#25]
Hi  

1) I ran` cat /vddos/vDDoS_Monitor.txt` and tried to access **vDDoS Admin Monitor TCP/UDP** page but I got ERROR 5XX as below. 
<a href="https://ibb.co/kLFSU7"><img src="https://preview.ibb.co/iueAhS/Screen_Shot_2018_04_16_at_1_34_47_PM.png" alt="Screen_Shot_2018_04_16_at_1_34_47_PM" border="0"></a>
2) Are these status/ monitoring page are protected against the public? 
3) There are 2 links to each Website  Status and one of it is 404. Is it normal?

Thank you so much.

**Comment by duy13** [comment]
```
[root@vDDoS ~]# cat /vddos/vDDoS_Monitor.txt
 
 vDDoS Admin Monitor: http://17.14.11.28/fd66552c3b-vddos-monitor
 vDDoS Admin Monitor TCP/UDP: http://17.14.11.28/fd66552c3b-tcp-udp-vddos-monitor
Website "ssl.ipserver.ml" Status: http://server.ml/e48426a2bd-status-monitor
Website "ssl.ipserver.ml" Status: https://server.ml/e48426a2bd-status-monitor
Website "default" Status: http://default/d1054118a3-status-monitor
Website "default" Status: https://default/e3ece7fa8f-status-monitor
```

1. vDDoS Admin Monitor TCP/UDP is a monitoring page for **TCP/UDP** proxies (not HTTP Proxy) looking for the _tcp-udp-proxy.conf_ file. If TCP/UDP Proxy is not enabled, there will be no information for you to view
2.  vDDoS Admin Monitor Page is a **random** and **secret** link after each restart vDDoS and change the server parameters
3. Because that domain is **not pointing** to the IP addr of vDDoS

**Comment by robert1112** [comment]
Hi @duy13 Thanks so much for your support. So I can also enable TCP/UDP proxies in vDDOS? Thank you.

**Comment by duy13** [comment]
TCP/UDP proxy used for Reverse Proxy other applications running TCP/UDP. 
For example: FTP, Game, DNS, SMTP, ...
Remember that vDDOS is not able to prevent ddos for that application, it only provides proxy functionality, to prevent ddos for TCP / UDP you use other tools, For example: CSF, Iptables, Deflate...
